### PR TITLE
#305 cleanup

### LINKED ISSUE #413: Regression in the returning of inspected labels
Since the commit 82b213b, the following command had returned an empty dict instead of fully populated Labels:

`skopeo --debug inspect docker://registry.access.redhat.com/rhosp12/openstack-nova-api:latest`

Since this is a regression and the revert is clean I'm going to propose a PR with the revert.

Whatever the fix, this affects builds of skopeo-0.1.28 so revendoring will be required.

### PR DESCRIPTION
**Pull request by mtrmac**
This is a set of quite independent cleanups and minor bug fixes on top of #305 .  Notably resolves #413, and adds tests for the schema1 code to decrease risk of similar breakage in the future.

See individual commit messages for more details. I’ll be happy to break this up into several PRs if any part needs more discussion than others.

Cc: @nalind 

- Simplify `types.Image.Inspect` call chain
- Make `ImageInspectInfo.Created` optional
- Move `LayerInfosForCopy` from `UnparsedImage` to `Image`/`sourcedImage`
- Populate labels in `manifest.Schema1.Inspect`
- Clean up manifest types
- Return `""` in `computeID` for unknown manifest types
- Instead of a type switch + cast + error, let the type switch do the conversion
- Rename `manifest.Schema1.ToSchema2` to `ToSchema2Config`
- Load a `*storage.Image` only once in `storageImageSource`
- Drop unused `storageImageDestination.{image,systemContext}`
- Create a new slice in `Schema1.UpdateLayerInfos`
- Add tests for `image.manifestSchema1`

### CODE REVIEW

**Comment by mtrmac** [comment]
This breaks API, so tests are going to fail; corresponding skopeo PR is https://github.com/projectatomic/skopeo/pull/477 .

**Comment by mtrmac** [comment]
@runcom ping

**Comment by runcom** [comment]
LGTM, @nalind please ack and I'll merge

File: manifest/docker_schema1.go [hunk 1]
```diff
@@ -202,44 +203,39 @@ func (m *Schema1) Inspect(_ func(types.BlobInfo) ([]byte, error)) (*types.ImageI
...
 		DockerVersion: s1.DockerVersion,
-		Labels:        make(map[string]string),
 		Architecture:  s1.Architecture,
 		Os:            s1.OS,
 		Layers:        LayerInfosToStrings(m.LayerInfos()),
-	}, nil
+	}
+	if s1.Config != nil {
+		i.Labels = s1.Config.Labels
+	}
```
Comment (nalind) [inline manifest/docker_schema1.go]: Does this leave `i.Labels` set to `nil` if the compat blob doesn't specify any labels?

**Comment by nalind** [comment]
One nit, otherwise LGTM.

File: manifest/docker_schema1.go (hunk 1 above)
Comment (mtrmac) [reply manifest/docker_schema1.go]: “A `nil` map is equivalent to an empty map except that no elements may be added.”, which seems acceptable here (and consistent with schema2).

**Comment by mtrmac** [comment]
👍
